### ISSUE TITLE
Rewrite docu to use k8s-helm-example as an example and not as a template

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#114]
**Reason**
Our https://github.com/catenax-ng/k8s-helm-example is marked as a template and also mentioned as a template repository in our "things to request" https://catenax-ng.github.io/docs/resources#github-repository-in-catenax-ng. 

The repository is meant as an example 'How to do things' but is too big / different to be used as a a template repository. A template repository would be an additional thing to maintain and not used very often. Its more critical to use to keep the k8s-helm-example up-to-date / shiny instead.

**AC**

- Move it to tractus x
- Rename it to perhaps: "k8s-base-example" etc.
- Rewrite mentions of k8s-helm-example to be used as an example and guidance but not as a template
- Unmark it as a template repo
- Revisit k8s-helm-example and clean it up / sync with current TRGs

**Additional information / links**

**Comment by SebastianBezold** [comment]
I think this issue can be closed, since it got a bit out of date.
We did not maintain the `k8s-helm-example` repo and workflows, that we once used as reference, are already more advanced and properly documented in our TRGs or other repos, that are already in `eclipse-tractusx`. 

We also do not create new repos in `catenax-ng` except forks. So a template repo is also not needed anymore.

If we DO NEED this repo in any form, we can reopen the issue
