### ISSUE TITLE
Not able to push a local branch to remote

### ISSUE THREAD

**Issue by nirschlk** [eclipse-tractusx/sig-infra#188]
**Please describe your request:**

I am not able to push a local branch to remote at https://github.com/catenax-ng/eclipse-tractusx.github.io
You invited me to join the https://github.com/catenax-ng organization may be you can help me. I think I need some more rights to create a branch.

I get the followings:
remote: Permission to catenax-ng/eclipse-tractusx.github.io.git denied to nirschlk.
fatal: unable to access 'https://github.com/catenax-ng/eclipse-tractusx.github.io/': The requested URL returned error: 403

**Comment by FaGru3n** [comment]
Hi @nirschlk thanks for opening the issue here again.

so basically spoken your not involed at this moment to work against the Eclipse Tractus-X GitHub organisation and the fork of this  https://github.com/catenax-ng/eclipse-tractusx.github.io is just a copy of the upstream repo in Eclipse Tractus-X.

The Fork is used to give you the posibility to work outside Eclipse Github Organisation but if you want to update the exising one your have to create a PR against the upstream repo in Eclipse Tractus-X or ask a committer within Eclipse Tractus-X to do that for you. https://projects.eclipse.org/projects/automotive.tractusx/who

And when you try it on yourown to update the docusaurus page the first starting point is here:
https://eclipse-tractusx.github.io/docs/oss/getting-started

**Comment by FaGru3n** [comment]
Any feedback or do you want a little chat?

If your fine with the result please review the issue and close it.

**Comment by nirschlk** [comment]
The access to the catena-ng was missing. I have been added to "catenax-ng" repository and everything works fine.
