### ISSUE TITLE
Issue function for the Standardisation Repository

### ISSUE THREAD

**Issue by evgenyvinokurov** [eclipse-tractusx/sig-infra#21]
I would like to have the issue function within this repository:
https://github.com/catenax-ng/product-catena-x-standardization

**Comment by carslen** [comment]
For the sake of courtesy, some content would have been nice :(

**Comment by evgenyvinokurov** [comment]
I apologise, I have discussed the issue with Fabian and Siegfried by phone. They have asked me to create an issue for documentation. That's why I didn't write any further content. 
Issue function is already there

**Comment by FaGru3n** [comment]
HI @evgenyvinokurov thanks for raising an issue so that we could also share what we already did for your private repostory 😉 

some hint for me did you deleted the pre defined issue template things and modified it by yourself? 

i would suggest raising empty issue should not be possible.

**Comment by FaGru3n** [comment]
already fixed in the following commit
https://github.com/catenax-ng/product-onboarding/pull/27/commits/7a238644dd3071a9388bee1d7347f013bcc7ae63

so issues are know working for your repository
https://github.com/catenax-ng/product-catena-x-standardization/issues

Please review and close the issue if your fine with it.
