### ISSUE TITLE
Access to the Standardisation Repository

### ISSUE THREAD

**Issue by evgenyvinokurov** [eclipse-tractusx/sig-infra#238]
Hello all,
 
Alexandre Loire @LoireGalia (Technical Committtee for Standardization – Member) is in the Standardization – Repository.
 
https://github.com/orgs/catenax-ng/teams/product-standardization?query=Loire
 
However, he cannot access the repository at the moment.
 
https://github.com/catenax-ng/product-catena-x-standardization
 
Could you please help us?

**Comment by carslen** [comment]
Checked membership of LoireGalia, seems fine.

![Image](https://github.com/eclipse-tractusx/sig-infra/assets/28647218/e0e58a63-3721-4cfa-9e79-84932c2d7d8c)

Since the repository product-catena-x-standardization is set to private, the repository is only accessible if you are logged in to GitHub. So we need to clarify what "no access to the repository" means. How is the repository accessed (WebUI, GIT CLI, etc.)?

**Comment by carslen** [comment]
Does the problem persist?

**Comment by evgenyvinokurov** [comment]
> Does the problem persist?

I will check it out. I'll get back to you as soon as I have the information.

**Comment by carslen** [comment]
Any updates on this issue? Otherwize I'd close this issues tomorrow.

**Comment by evgenyvinokurov** [comment]
Unfortunately, I have not heard from him. Therefore, I would suggest closing the issue.

**Comment by carslen** [comment]
OK, closing this issue for now. Feel free to reopen or create a new one if the error persist.
