### ISSUE TITLE
Dashboard shows archived repositories

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sig-infra#241]
**Is your support request related to a problem? Please describe.**  
As discussed in the office hours, following repositories have been archived but are still considered in the [Dashboard](https://eclipse-tractusx.github.io/sig-release/):
- https://github.com/eclipse-tractusx/puris-frontend
- https://github.com/eclipse-tractusx/puris-backend

**Describe the solution you'd like**  
Don't show the repositories. Either by evaluating github attributes or by adding a property to the .tractusx file (as discussed during the session).

**Additional context**  
Sidenote: We merged them into a [mono-repo](https://github.com/eclipse-tractusx/puris)

**Comment by SebastianBezold** [comment]
HI @tom-rm-meyer-ISST, thanks for opening the issue. I will take that on, as soon as the current quality gate phase is over. For the proposed solution: 
I think we won't hide the archived repos, but show them in a separate list or so. As long as they are archived and not deleted, we need to at least think about them, since they are still part of the Tractus-X project.
Will keep you posted on this topic!

**Comment by hzierer** [comment]
I will convert this ticket into a regular story for us to make planning easier.

**Comment by tomaszbarwicki** [comment]
Hi @tom-rm-meyer-ISST, added archived repos into separate section of the dashboard.
