### ISSUE TITLE
[TRG Check Dashboard] monorepos should not throw warnings

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/sig-infra#306]
checks on repositories containing multiple components (e.g. frontend + backend) should not throw warnings regarding TRG 1.02 + TRG 2.03

>  
> TRG-Check Pipeline: https://github.com/catenax-ng/tx-traceability-foss/actions/runs/6480134583/job/17595042382#step:3:53
>   
> 1) No warnings for files which are splitted in frontend / backend:
> See:  Testing Quality Guideline: TRG 1.02 - INSTALL.md
> See:  Testing Quality Guideline: TRG 2.03 - Repo structure
> 
> https://github.com/catenax-ng/tx-traceability-foss/blob/main/tx-backend/INSTALL.md
> https://github.com/catenax-ng/tx-traceability-foss/blob/main/frontend/INSTALL.md
> 
> 2) No failing Testing Quality Guideline: TRG 4.02 - Base images
> We are using cypress which is detected as base image and causing the base image validation step fails.
> - Detected: cypress/included:12.3.0

**Comment by tomaszbarwicki** [comment]
Hi @hzierer, is this really a dashboard issue? or more general quality checks tool related? can you provide an example of a monorepo for which it is an issue?

**Comment by SebastianBezold** [comment]
AFAIK, the warning for TRG 1.02 regarding a missing INSTALL.md is intended. This was meant to remind people, that it could be a good idea. But I also see, that it leads to confusion, especially in the monorepo case @hzierer mentioned.
I saw repos, where there have been `INSTALL.md` files, but in `/frontend` and `/backend` directories. In this case the reminder is odd, since they actually have the file. Just in a different place

For TRG 2.03, I only see potential issues regarding the `DEPENDENCIES` file name. In monorepos, we add `_FRONTEND` or `_BACKEND` suffixes. If we search for a fully matching `DEPENDENCIES`, this could lead to issues. The `INSTALL.md` issues from above could also be included in the repo structure check

**Comment by tomaszbarwicki** [comment]
@SebastianBezold I wouldn't say the reminder is odd since the check just follows [TRG description](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2)  which is very clear where the INSTALL.md should be located. At the moment I see that we either amend description first and check afterwards or recommend monorepo's guys to reference other INSTALL.md files of components within original one located at root.

**Comment by Siegfriedk** [comment]
We will get an exclusion mechanism which will make this green. We will also create a ticket to support monorepos and prioritize that accordingly
