### ISSUE TITLE
New Repository for the new Circularity KIT

### ISSUE THREAD

**Issue by LuisRickert** [eclipse-tractusx/sig-infra#318]
Repo name:  Circularity KIT

Purpose: The purpose of the repository is to develop and maintain the Circularity KIT

Responsible: @LuisRickert

**Comment by SebastianBezold** [comment]
Hi @LuisRickert and @danielmiehle,

is there now a consensus, if it is our desired workflow to have KITs outside the [eclipse-tractusx/eclipse-tractusx.github.io/](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/).
My assumption is still, that publishing KIT content can only happen through that repo and therefore some copy-pasting is happening at the end

As a reminder: I think there are the following issues with that workflow

- Contributors (non-committers) still need to fork in order to contribute.
- There is no way to see the rendered KIT content, since there is no underlying docusaurus setup
- PRs have to be reviewed twice. First for KIT repo, second for integrating in the project website
- Legal Documentation and open source compliance has to be tackled separately in the new repo

Hint: There is already a fork of the website repo in catenax-ng: https://github.com/catenax-ng/eclipse-tractusx.github.io

**Comment by SebastianBezold** [comment]
Hi @LuisRickert and @danielmiehle,

any thoughts on that? Is working on a fork of the website repo a valid option for you?

**Comment by LuisRickert** [comment]
Hi @SebastianBezold,
as far as i know there should one repository for a KIT within this [organisation](https://github.com/eclipse-tractusx), take the Eco-Pass KIT as [Example](https://github.com/eclipse-tractusx/eco-pass-kit). If the KIT developers want to add their KIT to the Tractus-X Website they fork the Tractux-X repository and create a Pull Request which contains their content. 
This process may be outdated but i could not finde some other process on the Tractus-X website.

**Comment by SebastianBezold** [comment]
Hi @LuisRickert,

I know that there are dedicated KIT repos. That's how i got to know the "cumbersome" workflow.
Also from my point of view as a committer, I want to reduce the overhead of having 2 reviews of the same content.
Since you mention Eco-Pass. This is actually one of these cases, where they have their [repo](https://github.com/eclipse-tractusx/eco-pass-kit) AND are published on our [website](https://eclipse-tractusx.github.io/docs-kits/kits/Eco_Pass_KIT/page-adoption-view)
So which content is up-to-date now? What if there have been review comments on the website PR? Are they reflected in the KIT repo as well?

@danielmiehle: It would be great if you can talk to the teams, who do maintain duplicated versions of their docs and ask them to stick with one approach.

**Comment by LuisRickert** [comment]
> Hi @LuisRickert,
> 
> I know that there are dedicated KIT repos. That's how i got to know the "cumbersome" workflow. Also from my point of view as a committer, I want to reduce the overhead of having 2 reviews of the same content. Since you mention Eco-Pass. This is actually one of these cases, where they have their [repo](https://github.com/eclipse-tractusx/eco-pass-kit) AND are published on our [website](https://eclipse-tractusx.github.io/docs-kits/kits/Eco_Pass_KIT/page-adoption-view) So which content is up-to-date now? What if there have been review comments on the website PR? Are they reflected in the KIT repo as well?
> 
> @danielmiehle: It would be great if you can talk to the teams, who do maintain duplicated versions of their docs and ask them to stick with one approach.

Yes , ik this is quite cumbersome and prone to errors. Irc the reasoning was that there may be content within the separate repo that the doesn't belong on the Tractus-X website. 

Nevertheless i still need a repository for the Circularity KIT where i can add its content and create a PR to the Tractus-X repository adding the Circularity KIT, which should be done unitl end of November

**Comment by SebastianBezold** [comment]
Would the fork in catenax-ng work for you? Also feel free to fork it to you personal account or company org

**Comment by LuisRickert** [comment]
In order to add the KIT content to the Tractus-X Website i already have an Tractus-X fork on my personal github account, which i'll use. 

Do i get that correctly that there won't be any dedicated KIT Repositories within the Tractus-x Org anymore?

**Comment by SebastianBezold** [comment]
That's why I mentioned @danielmiehle. I personally do not see the need of the dedicated repos, at least on the ones i look at. Like highlighted, I only see drawbacks. But to be fair, we did not align yet and should do that as soon as possible.
I guess a strict "we will never have that" won't happen, but we should way the pros and cons for every case.
What I could see as a good approach is, that every KIT starts in the website repo and only if we find content, that should go somewhere else, we will create the repo. But not as default starting choice.

@Siegfriedk what are your thoughts on that?

HINT: There is a [tutorial-resources repository](https://github.com/eclipse-tractusx/tutorial-resources). I could imagine, that KIT content, that's not a good fit for the website could be code samples or similar. Not sure if the tutorial-resources is a good fit, but maybe we can create a single repo, that all KITs share to put their non-website content. A directory structure could make it easy to share the repo

**Comment by FaGru3n** [comment]
Hi @Siegfriedk think you feedback is required here.

**Comment by SebastianBezold** [comment]
Hi @LuisRickert, talked again with @danielmiehle and we concluded, that we do not want to create separate KIT repos in the future, unless they would really contain implementations, that are not meant to be published on the website. 
Beside the implementations, separate repos in eclipse-tractusx do potentially lead to duplication, while also not providing the benefits hoped for.
We might also archive the three existing ones.

Closing this issue for now. Feel free to re-open it, if there is need for further discussion
