### ISSUE TITLE
New Environment

### ISSUE THREAD

**Issue by NSolutionDev** [eclipse-tractusx/sig-infra#321]
Purpose: Clarify how to exchange data with CatenaX data eco system
Requested by: NSolutionDev
End date of demonstration: 25.10.2024
Teams participating: simple data exchange

> ! Please be aware:   
> We do not provide dedicated environments for single teams. We will provide a DEV, INT, and 
PRE-PROD environment and teams will collectively use these environments together. A list of available environments can be found in the Catena-X Confluence.

**Comment by SebastianBezold** [comment]
Hi @NSolutionDev,

as the hint in the issue template already indicates, we do not create new environments lightly. 
Additionally, they are Catena-X Consortia puposes only. Since I did not yet recognize you during our activities (sorry if I missed something), could you please elaborate, which part of the Consortia you are involved in?

FYI: @danielmiehle, @giterrific, @Siegfriedk

**Comment by NSolutionDev** [comment]
Dear Mr Sebastian Bezold.

Currently I am investigating CatenaX system, and would like to join with
your team to contribute.
So if you have any testing environment, please invite me as an user then i
can login to handons the feature.
Also i have knowledge on K8S, ReacJS, so if there any thing i can
contribute please let me know.

Best Regards.

**Comment by SebastianBezold** [comment]
Hi @NSolutionDev,

ok understood, thanks for the input. 
Unfortunately the current testing infrastructure belongs to the Catena-X consortia and access to the underlying infrastructure can only be granted to consortia members. But I'm not 100% sure, so I'll se if I can find someone to confirm that.

Other possibilities to try out and test the current ecosystem are: 

- Checking out the KITs and their docs: https://eclipse-tractusx.github.io/developer
- Habe a look at the [tutorial-resources](https://github.com/eclipse-tractusx/tutorial-resources) repo 

 As general info: All of our Eclipse Tractus-X components, services and apps are aligned on Kubernetes as operation runtime environment and provide Helm Charts, that should give you a good starting point. Charts are always located in the `/charts` directory

**Comment by NSolutionDev** [comment]
Dear Mr. Senatian Bezold

Thank your very much for your email.
I will try to install the local environment to test.

Best regards.

**Comment by NSolutionDev** [comment]
Dear Mr. Sebastian Bezold

Thank you very much for your support.
I am installing MXD and faced with this kind of error?
My env is KinD
If you have experience on this, please help me.
Thank you very much.
│ Error: Internal error occurred: failed calling webhook "
objects.hnc.x-k8s.io": failed to call webhook: Post "
https://hnc-webhook-service.hnc-system.svc:443/validate-objects?timeout=2s":
no endpoints available for service "hnc-webhook-service"
│
│   with kubernetes_config_map.keycloak-realm,
│   on keycloak-realm.tf line 20, in resource "kubernetes_config_map"
"keycloak-realm":
│   20: resource "kubernetes_config_map" "keycloak-realm" {

**Comment by SebastianBezold** [comment]
Hi @NSolutionDev,

unfortunately I am not too deep into MXD and cannot help you out here. 
But there are two project communication channels, that you can use to ask such questions:

- The Mailing List: https://projects.eclipse.org/projects/automotive.tractusx/contact
- The Eclipse Matrix Chat Space for Tractus-X: https://matrix.to/#/#automotive.tractusx:matrix.eclipse.org

There are plenty of rooms, but the "Tractus-X" one is the entrypoint, where hopefully someone can forward you to the right channel if needed.

I'll close this support issue for now, since I got confirmation, that we cannot invite you to use the consortium infrastructure
