### ISSUE TITLE
Enable Issues on https://github.com/catenax-ng/product-ontology for Planning to @igorsvetlov

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/sig-infra#324]
Please enable Issues on https://github.com/catenax-ng/product-ontology
for planning to me.

**Comment by SebastianBezold** [comment]
HI @igorsvetlov,

usually, we do not activate issues on catenax-ng repositories, since this org is just a step in between moving to [eclipse-tractusx](https://github.com/eclipse-tractusx).
In the long term, catenax-ng will most likely be removed/archived as a GitHub Org and therefore the whole planning effort lost.

So I would ask you to consider planning on the respective eclipse-tractusx repositories.
Right now I am not sure, but isn't ontology already migrated to repository in our Eclipse GitHub org? This here maybe? https://github.com/eclipse-tractusx/knowledge-agents

**Comment by SebastianBezold** [comment]
Hi @stephanbcbauer,

want to take you into the loop, because in the meantime, I got a hint, that this support issues has its roots in [this issue](https://github.com/eclipse-tractusx/sig-release/issues/280) from the open planning.

What are your thoughts on that. Is there already some kind of guidance on how teams can plan their "sub-stories" to the overarching issues?

My suggestion is still, to have the "sub-stories" as issues on the component repository. In this case I guess one of the "knowledge" repos. Then you can link the "sub-story" to the overarching issue. This is totally possible across repos 

The Story text from the comments could just be used as issue description and linked. This would also have the benefit of seeing the status (open/closed) on the overarching issue.

**Comment by stephanbcbauer** [comment]
@SebastianBezold , @igorsvetlov to be honest we didn't talk/think about linking issues from catenax-ng to tractus-x. Cause we always thought about open source and thats tractus-x. And i wouldn't like to mix it.

I agree and like @SebastianBezold suggestion. Is there a tractus-x repository which could be a fit for your created sub-stories?

Is there already a plan to move your repositories from catenax-ng to tractus-x?

**Comment by SebastianBezold** [comment]
Hi @igorsvetlov,

would it be ok for you to use the repositories on eclipse-tractusx for further planning?
In case you want to set labels and are not yet added as "Tractus-X project contributor", feel free to open an issue here using [this template](https://github.com/eclipse-tractusx/sig-infra/issues/new?assignees=&labels=support&projects=&template=support-add-project-contributor.md&title=New+Tractus-X+project+contributor)

If there are missing labels, that you need for your planning, just reach out to any committer, via mailing list or Matrix chat. Every committer can create labels on the eclipse-tractusx repositories

**Comment by SebastianBezold** [comment]
I'll close the issue for now. If there are any further questions @igorsvetlov, feel free to reopen it
