### ISSUE TITLE
Support for puml workflow

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sig-infra#329]
**Is your support request related to a problem? Please describe.**  
We introduced the new puml to svg workflow but we are not sure how to correctly unzip and commit the files to the respective directory.

We got this [workflow](https://github.com/eclipse-tractusx/puris/actions/runs/6696798031) run creating the artifacts correctly.

**Describe the solution you'd like**  
I would like to add the following steps to the workflow:
- clone repo
- unzip and add files
- commit files 

potential problem: the commit MUST be signed by someone who signed the ECA (commonly the person triggering the run or the merge). Else the Eclipse Contributor Agreements will fail.

**Additional context**  
It makes sense to update the examples referenced in the [TRG Draft](https://eclipse-tractusx.github.io/docs/release/trg-0/trg-1-4) then accordingly :)

**Comment by tom-rm-meyer-ISST** [comment]
@FaGru3n, I would be grateful, if you could support! :)

**Comment by FaGru3n** [comment]
Hi @tom-rm-meyer-ISST,

great to hear that this workflow is needed and my work is appreciated. 😉 

> potential problem: the commit MUST be signed by someone who signed the ECA (commonly the person triggering the run or the merge). Else the Eclipse Contributor Agreements will fail.

Jep as you already get aware of upcomming problems i leave this part open to everyone to use it, because this depends on the team or strategies our teams are working. (I am thinking of approvals, committing rules, pull-requests, preview, forking, etc.)

If you want to change the behaviour you could also add more step´s / jobs to your workflow [here](https://github.com/eclipse-tractusx/puris/blob/3ff6987e3642253695735f753b46abb0c3e1be73/.github/workflows/render-puml-to-svg.yml#L52)

That´s why i add the comment, that you can now decide how you want to interact with the files like storing it into a separate branch or open a PR and commit it there. There are some cool ways on the [GitHub Marketplace](https://github.com/marketplace) available and someone need a specific GitHub Token. (Please be patient with licences etc.)

Also a great help for me using the default permissions for a generated GitHub Token on the workflow run you can find here: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3705

> You could just use the standard {{ secrets.GITHUB_TOKEN }} that is setup for your workflow automatically to avoid running into rate limits.
If you need additional permissions, request them as explained here: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

But as you said it, needs some fine set-up how you want to handle the storing part.

**Comment by FaGru3n** [comment]
FYI closed this one 😉
