### ISSUE TITLE
Secret Request for Catena Git

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/sig-infra#330]
**Is your support request related to a problem? Please describe.**  
Missing a secret for end to end tests configuration.
**Describe the solution you'd like**  
Adding a secret to be able to start writing end to end tests to be prepared once we change it to the tractus-x like e2e tests.

**Additional context**  
Please get in contact with me to get SECRET info. 

Thanks in advance.

**Comment by tomaszbarwicki** [comment]
@ds-mwesener could you please specify repository for which you need a secret creation?

**Comment by ds-mwesener** [comment]
> @ds-mwesener could you please specify repository for which you need a secret creation?

HI @tomaszbarwicki 
https://github.com/catenax-ng/tx-traceability-foss

**Comment by SebastianBezold** [comment]
Hi @ds-mwesener,

since you want to add the secret to a fork from eclipse-tractusx, I think you should reconsider the approach.
Correct me if I am wrong, but I guess you want to configure consoria specifics here, Like we discussed earlier regarding the cypress workflows, we need to keep them clean from consortia specifics.

My suggestion would be to either add a manual workflow, where you can provide the secrets/credentials via input, or try to avoid secrets at all.

**Comment by ds-mwesener** [comment]
Hi @SebastianBezold, I have discussed the topic regarding the e2e tests with my product owners. We want to go into the right direction. Currently we need a quick solution for writing tests already, so that we can simply use them for the future in the right e2e configuration. 

As we want to have an automatic trigger on that e2e tests, providing manual input would not fit our requirements. 

Please assist. Thanks

**Comment by SebastianBezold** [comment]
Hi @ds-mwesener,

I can understand that. Can you elaborate on what kind of information you want to store in that secret?
We had plenty of cases like this in the past and that always lead to complicated workflows, that had to include exceptions for eclipse-tractusx. Sooner or later, your workflows, that reference the secret, that is present in catenax-ng will end up in eclipse-tractusx. There it will fail, since the secret is not present.
So other teams added conditions on workflow steps, that only run them if triggered in catenax-ng.
But actually we do want to move away from these kind of hacks and most of the teams already managed to do so by treating eclipse-tractusx as leading and not have consortium specifics in the workflow.

If you can further describe what the secret is needed for, I bet we can find a good solution

**Comment by ds-mwesener** [comment]
We want to store login information to retrieve a bearerToken for authenticating a user. Afterwards we will be able to write cypress tests to increase the quality of our trace-x frontend. 

In a later scenario, once we have a full functional e2e testsetup in a manner of open source eclipse-tractusx. We do not need this anymore, because we can setup and use credentials within a e2e testcontainer or similar.

**Comment by SebastianBezold** [comment]
Hi @ds-mwesener,

so if you really cannot find any other way than the consorita specific secret, we can add it, but I would actually like to keep it as a PoC approach only and revisit it in near future. Not having another prototype, that lives forever.
Are you planning on keeping it in catenax-ng and contributing to eclipse-tractusx, only as soon as there is a sustainable solution?

How do you want to exchange the secret information, so we can add it?

**Comment by ds-mwesener** [comment]
> Hi @ds-mwesener,
> 
> so if you really cannot find any other way than the consorita specific secret, we can add it, but I would actually like to keep it as a PoC approach only and revisit it in near future. Not having another prototype, that lives forever. Are you planning on keeping it in catenax-ng and contributing to eclipse-tractusx, only as soon as there is a sustainable solution?
> 
> How do you want to exchange the secret information, so we can add it?

Hi @SebastianBezold the plan is to not contribute it to eclipse, since it is only enabling us to run / validate newly created e2e tests. 
Once a sustainable e2e open source test setup is existing for eclipse-tractusx we want to switch over to this approach. 

Then we will already have a lot of tests which can be used in this future setup.

I have added the secrets already to the vault and shared with @tomaszbarwicki - can we proceed with that?

Thanks in advance!

**Comment by SebastianBezold** [comment]
Hi @ds-mwesener,

ah ok cool. Yes Vault is perfect. @tomaszbarwicki could you already add to the repo?

**Comment by tomaszbarwicki** [comment]
@ds-mwesener all secrets added, pls confirm after tests and close the issue if works as expected

**Comment by ds-mwesener** [comment]
Hi @tomaszbarwicki Thanks it works.
