### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/sig-infra#34]
new GitHub user
Use name : koptan

Question from us: 
oliver.schlien@zf.com 

Vouching person: 
oliver.schlienz@zf.com

**Comment by carslen** [comment]
User has been invited to GH org catenax-ng. After invitation have been accepted a GH team maintainer can add him to their GH team.

Please keep in mind to use the GH username only for next "invite member" tickets due to privacy reasons. The email address is not required but it's viewable to all GH users in this issue.

**Comment by OSchlienz** [comment]
Thanks for the info!
