### ISSUE TITLE
Make Office Hour Open

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#355]
**Description**

As a wish form the PCWM Workshop there we should make the Office Hour public available.

**AC**
- [ ] Recording is public available
- [ ] Meeting-Minutes are present in the ETX Web Page
- [ ] Agenda is updated to inform everyone that this Meeting will be public available to prevent internal information shared
- [ ] Links are present somehow
- [ ] Anti Trust paper will needed
- [ ] Information is shared what could be presented

**Comment by FaGru3n** [comment]
asked Angelika for the Anti-Trust Default from Eclipse Foundation, see https://www.eclipse.org/org/documents/Eclipse_Antitrust_Policy.pdf

Do we need to make a separation from Tractus-X to Catena-X / Consortia / and the assoiaction?

**Comment by FaGru3n** [comment]
Hi @SebastianBezold guess this is also interesting for you, because you already involed further steps to have an more open round.

**Comment by SebastianBezold** [comment]
From my point of view, this issue can be closed directly. This most of the things are already discussed or irrelevant.
Summary for bullet points in description:

- Recording:  We won't publish any recordings. We also won't record
- Meeting-minutes: There is a place for meeting minutes: https://eclipse-tractusx.github.io/community/meeting-minutes. Added via this directory: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/tree/main/blog-meeting-minutes
- Agenda: If there are special topics, it can also be announced via the blog mentioned before
- Links: Meeting links only open topic, but will be addressed by the association
- Anti trust: No special anti trust statement needed from my point of view. If it is needed, we can track that in a different issue
- Information shared: ? I guess also the blog or mailing list


@FaGru3n not sure what else to do with this issue, since it's nothing to "tick of". In my opinion, there is enough information available, that we do not need to document extra things. If we find missing info, I would just add that as soon as we encounter it. Don't think we need to plan or track that as issue. What do you think?
