### ISSUE TITLE
TRG 1.0X: Add new TRG for /docs folder

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#361]
The /docs folder has a hard requirement to be basedon arc42. We do not have any TRG referencing the docs folder therefore we create one.

AC:
- Create new TRG for /docs folder explaining the usage of arc42
- Write to Daniel/Roland/Maillinglist and ask them if there is more documentation to arc42 in the public which we should link

**Comment by FaGru3n** [comment]
Hi @danielmiehle and @RolaH1t do you have more advisories what we try to achive with the arc42 documentation? 

Thanks in advance.

**Comment by FaGru3n** [comment]
FYI @kelaja and @vialkoje i would close this issue here, maybe you can adpot the description or some suggestions form the draft pr for the recommeded information for arc42 documentation... 

In case you have some feedback or questions regarding the pr, feel free to have a little chat.

Also FYI @Siegfriedk @danielmiehle
