### ISSUE TITLE
No access to product repository settings

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sig-infra#441]
**Is your support request related to a problem? Please describe.**  

Currently in settings tab I only have access to the submenu "Code security and analysis". Thus I can't set credentials to e.g., configure secrets and deploying keys.

**Describe the solution you'd like**  

I would like to have access to the respective options in the [PURIS repository](https://github.com/eclipse-tractusx/puris).

**Additional context**  

We found this issue during setting up owasp zap with @RoKrish14

**Comment by FaGru3n** [comment]
Hi @tom-rm-meyer-ISST,

our repoistories within https://github.com/eclipse-tractusx are maintained by the Eclipste Foundation. We can only manage settings via otterdog within https://github.com/eclipse-tractusx/.eclipsefdn

But if you would like to add secrets for the repo [PURIS repository](https://github.com/eclipse-tractusx/puris) you can raise a GitLab Issue for the Eclipse Foundation.

**Comment by FaGru3n** [comment]
Hi @tom-rm-meyer-ISST,

for the secrets you are right that otterdog will not help here, this was just a general information what we can change / request with repositories within eclipse tractus-x.

But as you already rasied the issue for the secrets by EF GitLab i would close the issue here.

If you need further help feel free to reopen the issue. Thanks in advance.
