### ISSUE TITLE
GitHub: New repository 

### ISSUE THREAD

**Issue by BeFranke** [eclipse-tractusx/sig-infra#478]
Required information:
- Details to your GitHub repository: product-behaviour-twin-demo
- Details to GitHub team to grant access: https://github.com/orgs/catenax-ng/teams/product-behaviour-twin-pilot

validation / approved by: BeFranke

@afederl 
@HeinrichAD
@tobikleinfrd

**Comment by FaGru3n** [comment]
Hi @BeFranke,

little question should this new repo be stored under the eclipse-tractusx GitHub organisation or under the catenax ng organisation?

Thanks in advance.

**Comment by BeFranke** [comment]
Hi @FaGru3n,

please create it under catenax-ng.

**Comment by FaGru3n** [comment]
Hi @BeFranke. after a little discussion within the team would be the best to start directly within eclipse tractusx because of the short time till consortia end.

Is it possible for your to raise a issue directly to the eclipse fountation or could we add it directly here via otterdog? Then we could be sure that the repo will take place after consortia phase.

**Comment by FaGru3n** [comment]
Hi @BeFranke i would close this issue for now... if there is some feedback or further questions feel free to reopen the issue. 

Thanks in advance.
